---
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get -y install lftp

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -b html source build/html

after_success:
  - |
      if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
        rm -rf build/html/.buildinfo build/html/.doctrees
        lftp -u "$FTP_USERNAME,$FTP_PASSWORD" -e 'mirror -R --delete build/html betacloud; exit;' sftp://betacloud.io
      fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#betacloud"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
